---
label: Project
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: body
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Body Text
- name: tags
  type: tag_list
  default: []
  label: Tags
- name: images
  type: field_group_list
  fields:
  - name: image
    type: file
    config:
      maxSize: 64
    label: Image
  - name: caption
    type: text
    config:
      required: false
    label: Caption
  config:
    min: 
    max: 
    labelField: 
  label: Images
